services:
  web:
    image: lance2785/beesafe-web # lien du repo dockerhub quand l'image est publiée
    #build: . pas utile si image déjà dans le repo local
    container_name: WEB
    environment:
      DB_SERVERNAME: DATABASE
      DB_NAME: lamp_db
      DB_USER: benjamin
      DB_PASSWORD: Absentee-Thaw-Blinker7
    networks:
      - website-network
    ports:
      - "80:80"
    restart: unless-stopped

  database:
    image: lance2785/beesafe-db
    container_name: DATABASE
    environment:
      MYSQL_ROOT_PASSWORD: Glutinous-Nylon4-Jawed
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: benjamin
      MYSQL_PASSWORD: Absentee-Thaw-Blinker7
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - website-network
    ports:
      - "3306:3306"
    restart: unless-stopped

  bind9:
    image: lance2785/beesafe-dns
    container_name: DNS
    environment: 
      - BIND9_USER=root
      - TZ=Europe/Paris
    networks:
      - website-network
    ports:
      - 53:53/udp
      - 53:53/tcp
    restart: unless-stopped

      
networks:
  website-network:
    driver: bridge